### PR TITLE
Add iCalendar support

### LINKED ISSUE #104: send iCalendar invites
Hi,
is anybody working on this feature: https://community.openproject.org/work_packages/3953/activity ?
I would need it and I can try to implement it but I'm not really a Ruby expert.

### PR DESCRIPTION
**Pull request by fbertone**
Adds basic support for iCalendar notifications.
Closes #104 
### What it does:
- Adds a button to send iCalendar **notifications** (method PUBLISH) via email to all invited users
### What is not included:
- Locales other than English
- Tests
- Support for sending _updates_ / _cancel_ notifications
### What can / should be improved:
- Insert agenda items into description
- Use method=REQUEST instead of method=PUBLISH
- Any **substantial** modification (e.g. start/end time) should increment the sequence number of the calendar object

### CODE REVIEW

**Comment by fbertone** [comment]
Any feedback? 
Are you interested in this feature or I should create a new plugin?

**Comment by oliverguenther** [comment]
Hey @fbertone,

sorry for the late reply, it seems we have missed the notifications for this PR. :confused:

Huge thanks for your contribution. If you haven't already created a plug-in, I'd like this to be merged into meetings. Let me give this a quick whirl myself and see if it works fine.

Best,
Oliver

**Comment by oliverguenther** [comment]
Seems to work fine, however i think it shouldn't be too hard to actually generate an ICS (without creating it manually) and send that as a file instead. Would that be useful for your use-case as well?

We can employ https://github.com/icalendar/icalendar/ for that task.

**Comment by fbertone** [comment]
Hi @oliverguenther , thank you for the reply.
Yes, all I need is a way to send ics data so that invitees can automatically add the event to their calendar, it doesn't really matter how the data is generated.
I created the ICS manually because it was the quickest way for me but of course you are free to integrate whatever you think it's better.
A more complete solution should also handle events modification and cancellation (sending update ics) but even sending just the initial invitation in already better than nothing.

**Comment by oliverguenther** [comment]
I think we can live without updates and cancellation and such, but I'd prefer to offload the ics generation to a gem since it's not something I can manage manually. I'll see if I can integrate that in a quiet minute and let you know!

**Comment by oliverguenther** [comment]
Hey @fbertone ,

I've based the suggested changes from my comment your work in #118, thus closing this PR. Please comment / test over at the other PR. Thanks again for your contribution!

Best,
Oliver

**Pull request closed without merging**
