### PR TITLE
Add iCalendar support

### LINKED ISSUE #104: send iCalendar invites
Hi,
is anybody working on this feature: https://community.openproject.org/work_packages/3953/activity ?
I would need it and I can try to implement it but I'm not really a Ruby expert.

### PR DESCRIPTION
**Pull request by oliverguenther**
This extends #107 with several features:
1. Use the icalendar gem for ics generation instead of manually writing it
2. Attach the ics alongside a proper mail body
3. Add a permission to the button

**Original PR (https://github.com/finnlabs/openproject-meeting/pull/107)**

Adds basic support for iCalendar notifications.
Closes #104 
### What it does:
- Adds a button to send iCalendar **notifications** (method PUBLISH) via email to all invited users
### What is not included:
- Locales other than English
- Tests
- Support for sending _updates_ / _cancel_ notifications
### What can / should be improved:
- Insert agenda items into description
- Use method=REQUEST instead of method=PUBLISH
- Any **substantial** modification (e.g. start/end time) should increment the sequence number of the calendar object

### CODE REVIEW

**Comment by fbertone** [comment]
It seems ok to me.
A small "issue" is that it doesn't set the field ORGANIZER and (for example) in gmail it shows "Unknown Organizer".
I think it would be better to set it to meeting.author as I was doing.
Apart from that I think it is good merge.
Thank you

**Comment by fbertone** [comment]
Hi,
just reminding that this PR is open

**Comment by oliverguenther** [comment]
Hey @fbertone, I've just added the `ORGANIZER` field.

@machisuji: Could you take a look at this PR?

**Comment by machisuji** [comment]
@oliverguenther I'll have a look.

**Comment by fbertone** [comment]
Hi,
any chance to see this merged anytime soon? ;)

**Comment by c-nv-s** [comment]
Also waiting for this to be merged.
Once merged you should also be able to close feature [https://community.openproject.com/work_packages/3953/activity](url)

**Comment by oliverguenther** [comment]
I discussed this with @machisuji and he was fine to merge this. Please note that this requires an additional permission to be set, which is not seeded by default.

**Pull request merged**
