### PR TITLE
Activity icon labels 2250

### PR DESCRIPTION
**Pull request by tilt**
https://www.openproject.org/work_packages/2250

:exclamation: Has to be merged before https://github.com/opf/openproject/pull/814

### CODE REVIEW

**Comment by hschink** [comment]
@tilt `icon-meeting-agenda`, `icon-meeting`, and probably `icon-meeting_minute` (didn't check the last one) is still missing (Just create a meeting with agenda/minutes and have a look into the activities view to reproduce the error)

**Comment by tilt** [comment]
@hschink Yes, but I think this is out of scope of the ticket and a matter of missing icon fonts. At least I thought so. Let's discuss this tomorrow.

**Comment by hschink** [comment]
@tilt All icons for the three classes mentioned above are still missing. Let's have a look on my review system when you're in the office.

**Comment by tilt** [comment]
There's

<pre>
dt > .icon-meeting:before {
  content: "\e057";
}
dt > .icon-meeting-agenda:before {
  content: "\e023";
}
dt > .icon-meeting-minutes:before {
  content: "\e022";
}
</pre>

I'll check out if there are underscores instead of dashes where the classes are defined later

**Comment by tilt** [comment]
@hschink Could you show me where the icons are referenced using underscored classes?

**Pull request merged**
